### ISSUE TITLE
Please review

### ISSUE THREAD

**Issue by msambridge** [inlab-geo/pyrf96#1]
This is a new repository that provides a ctypes interface to the Shibutani Fortran receiver function code. The expectation is that this will free us from use of f2p in CoFI, which is used by the current espresso version. I think it all works, but would appreciate any feedback on bugs or issues. Indeed feel free to just fix them and update.

**Comment by fmagrini** [comment]
I created a new environment using `mamba` and tried to install the package with `pip`. At first, I encountered errors, which I resolved by installing `gfortran` in my environment with:

```bash
mamba install gfortran
```

I was then able to successfully install the package with:

```bash
pip install git+https://github.com/inlab-geo/pyrf96
```

In Python, I tried to import the library by typing:

```python
import pyrf96
```

However, I got errors due to missing dependencies (`numpy` and `matplotlib`). After installing these dependencies, I was able to run the example on the homepage.

This suggests that it would be beneficial to have a `setup.py` file listing all required dependencies, so they are automatically installed if missing when pip-installing the package.

**Comment by auggiemarignier** [comment]
The dependencies go in the `pyproject.toml`.  I'm on it

**Comment by auggiemarignier** [comment]
There's an issue with editable installs `pip install -e .` but that can be ignored for now.

**Comment by msambridge** [comment]
Whats an editable install?

**Comment by auggiemarignier** [comment]
It means when you're developing a python package you don't have to keep doing `pip install .` when ever you make changes and want to run tests.  It basically puts a link in your environment to your working directory rather than doing a full install of the package.
